version: "2"
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "${DOCKER_SERVER_PORTS}"
    depends_on:
      - mongo
      - redis
      - rabbitmq
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    env_file:
      - .env
    ports:
      - "${DOCKER_MONGO_PORTS}"
  mongo_seed:
    image: mongo
    links:
      - mongo
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh
    depends_on:
      - mongo
  redis:
    container_name: redis-server
    image: redis
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: rabbitmq-server
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

